"""Bridge continuous Bayesian posterior draws to target-safe finite design.

This is a deterministic demonstration, not an empirical case study. It mimics draws
from an invasion-control model with continuous spread and control-effect parameters,
then treats those draws as a finite posterior support for reportability analysis.
"""
from __future__ import annotations

import json
import math
import random
from dataclasses import asdict, dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_JSON = ROOT / "artifacts" / "paper_b_posterior_bridge.json"
OUT_TEX = ROOT / "manuscript" / "generated" / "paper_b_posterior_bridge_table.tex"
SEED = 20260723
SAMPLE_SIZES = (500, 2000, 10000)
FALSE_RESOLUTION_LIMIT = 0.05


@dataclass(frozen=True)
class Draw:
    control_effect: float
    spread_rate: float
    source_class: int


def generate_draws(n: int = max(SAMPLE_SIZES), seed: int = SEED) -> list[Draw]:
    rng = random.Random(seed)
    draws = []
    for _ in range(n):
        high_response = rng.random() < 0.5
        control_effect = min(
            0.98,
            max(0.02, rng.gauss(0.78 if high_response else 0.38, 0.055)),
        )
        spread_rate = min(0.95, max(0.05, rng.gauss(0.38, 0.09)))
        draws.append(Draw(control_effect, spread_rate, rng.randrange(4)))
    return draws


def management_target(draw: Draw) -> str:
    margin = draw.control_effect - 0.45 * draw.spread_rate - 0.48
    return "eradication" if margin >= 0.0 else "containment"


def response_assay(draw: Draw) -> dict[str, float]:
    margin = draw.control_effect - 0.45 * draw.spread_rate - 0.48
    high_probability = 1.0 / (1.0 + math.exp(-40.0 * margin))
    return {"low": 1.0 - high_probability, "high": high_probability}


def source_trace(draw: Draw) -> dict[str, float]:
    return {f"source-{draw.source_class + 1}": 1.0}


def posterior_target_masses(
    draws: list[Draw], kernel, outcome: str
) -> dict[str, float]:
    masses = {"eradication": 0.0, "containment": 0.0}
    total = 0.0
    for draw in draws:
        weight = kernel(draw).get(outcome, 0.0)
        masses[management_target(draw)] += weight
        total += weight
    if total <= 0.0:
        raise ValueError("outcome has zero predictive mass")
    return {target: mass / total for target, mass in masses.items()}


def predictive_distribution(draws: list[Draw], kernel) -> dict[str, float]:
    result: dict[str, float] = {}
    for draw in draws:
        for outcome, probability in kernel(draw).items():
            result[outcome] = result.get(outcome, 0.0) + probability / len(draws)
    return result


def resolved(masses: dict[str, float], limit: float = FALSE_RESOLUTION_LIMIT) -> bool:
    return 1.0 - max(masses.values()) <= limit + 1e-12


def target_resolution_probability(draws: list[Draw], kernel) -> float:
    total = 0.0
    for outcome, probability in predictive_distribution(draws, kernel).items():
        if resolved(posterior_target_masses(draws, kernel, outcome)):
            total += probability
    return min(1.0, max(0.0, total))


def summarize(draws: list[Draw]) -> dict[str, object]:
    eradication_probability = sum(
        management_target(draw) == "eradication" for draw in draws
    ) / len(draws)
    response_resolution = target_resolution_probability(draws, response_assay)
    source_resolution = target_resolution_probability(draws, source_trace)
    selected = "response_assay" if response_resolution > 0.0 else None
    return {
        "posterior_draws": len(draws),
        "eradication_probability": eradication_probability,
        "containment_probability": 1.0 - eradication_probability,
        "response_assay_resolution_probability": response_resolution,
        "source_trace_resolution_probability": source_resolution,
        "target_safe_choice": selected,
    }


def latex_table(rows: list[dict[str, object]]) -> str:
    body = []
    for row in rows:
        body.append(
            f"{row['posterior_draws']} & "
            f"{row['eradication_probability']:.4f} & "
            f"{row['response_assay_resolution_probability']:.4f} & "
            f"{row['source_trace_resolution_probability']:.4f} & "
            f"Response assay \\\\"
        )
    return """% Generated by scripts/analyze_paper_b_posterior_bridge.py; do not edit.
\\begin{table}[ht]
\\centering
\\caption{Posterior-sample bridge from a continuous invasion-control model to finite target-safe analysis. The same experiment is selected as posterior support is refined.}
\\label{tab:posterior-bridge}
\\begin{tabular}{rrrrl}
\\toprule
Posterior draws & $P$(eradication) & Response resolution & Source resolution & Selected follow-up \\\\
\\midrule
""" + "\n".join(body) + """
\\bottomrule
\\end{tabular}
\\end{table}
"""


def run() -> dict[str, object]:
    all_draws = generate_draws()
    rows = [summarize(all_draws[:n]) for n in SAMPLE_SIZES]
    report = {
        "schema_version": 1,
        "seed": SEED,
        "false_resolution_limit": FALSE_RESOLUTION_LIMIT,
        "interpretation": "deterministic posterior-sample demonstration, not empirical data",
        "rows": rows,
        "draw_definition": asdict(all_draws[0]),
    }
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_TEX.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(report, indent=2), encoding="utf-8")
    OUT_TEX.write_text(latex_table(rows), encoding="utf-8")
    return report


if __name__ == "__main__":
    print(run())
