"""Generate deterministic Paper B figures and a compiled manuscript source."""
from __future__ import annotations

import runpy
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BENCHMARK = ROOT / "scripts" / "simulate_paper_b_benchmark.py"
ROBUSTNESS = ROOT / "scripts" / "analyze_paper_b_reviewer_robustness.py"
POSTERIOR_BRIDGE = ROOT / "scripts" / "analyze_paper_b_posterior_bridge.py"
MANUSCRIPT = ROOT / "manuscript" / "paper_b_main.tex"
REVIEWER_SECTIONS = ROOT / "manuscript" / "paper_b_reviewer_sections.tex"
COMPILED_MANUSCRIPT = ROOT / "manuscript" / "paper_b_compiled.tex"
OUT_DIR = ROOT / "manuscript" / "generated"
OUT_CONTRAST = OUT_DIR / "paper_b_experiment_contrast.tex"
OUT_OUTCOMES = OUT_DIR / "paper_b_strategy_outcomes.tex"

STRATEGY_LABELS = {
    "state_only": "State-only",
    "full_identification": "Full identification",
    "full_world_eig": "Full-world EIG",
    "target_safe": "Target-safe",
}


def _fmt(value: float) -> str:
    return f"{value:.6f}"


def _baseline_rows(report: dict[str, object]) -> list[dict[str, object]]:
    rows = [
        row for row in report["rows"]
        if row["architecture"] == "independent"
        and row["state_detection_sensitivity"] == 0.95
        and row["response_typing_accuracy"] == 0.99
        and row["common_failure_probability"] == 0.0
    ]
    order = tuple(STRATEGY_LABELS)
    return sorted(rows, key=lambda row: order.index(row["strategy"]))


def experiment_contrast_tex(report: dict[str, object]) -> str:
    contrast = report["benchmark_contrast"]
    gains = contrast["full_world_information_gain_bits"]
    resolutions = contrast["target_resolution_probability"]
    return rf"""% Generated by scripts/render_paper_b_figures.py; do not edit.
\begin{{tikzpicture}}[font=\small]
  \begin{{axis}}[
    ybar, bar width=18pt, width=0.82\linewidth, height=6.2cm,
    ymin=0, ymax=2.15, ylabel={{Information or target resolution}},
    symbolic x coords={{Response experiment,Nuisance experiment}}, xtick=data,
    x tick label style={{align=center}},
    legend style={{at={{(0.5,-0.23)}},anchor=north,legend columns=2}},
    nodes near coords, nodes near coords style={{font=\scriptsize}},
  ]
    \addplot coordinates {{(Response experiment,{_fmt(gains['response'])}) (Nuisance experiment,{_fmt(gains['nuisance'])})}};
    \addplot coordinates {{(Response experiment,{_fmt(resolutions['response'])}) (Nuisance experiment,{_fmt(resolutions['nuisance'])})}};
    \legend{{Full-world information gain (bits),Target-resolution probability}}
  \end{{axis}}
\end{{tikzpicture}}
"""


def strategy_outcomes_tex(report: dict[str, object]) -> str:
    rows = _baseline_rows(report)
    coordinates = {metric: [] for metric in ("correct_probability", "wrong_probability", "ambiguity_probability")}
    for row in rows:
        label = STRATEGY_LABELS[row["strategy"]]
        for metric in coordinates:
            coordinates[metric].append(f"({{{label}}},{_fmt(row[metric])})")
    return rf"""% Generated by scripts/render_paper_b_figures.py; do not edit.
\begin{{tikzpicture}}[font=\small]
  \begin{{axis}}[
    ybar stacked, bar width=22pt, width=0.96\linewidth, height=7cm,
    ymin=0, ymax=1.02, ylabel={{Terminal-report probability}},
    symbolic x coords={{{','.join(STRATEGY_LABELS.values())}}}, xtick=data,
    x tick label style={{rotate=20,anchor=east}},
    legend style={{at={{(0.5,-0.34)}},anchor=north,legend columns=3}},
  ]
    \addplot coordinates {{{' '.join(coordinates['correct_probability'])}}};
    \addplot coordinates {{{' '.join(coordinates['wrong_probability'])}}};
    \addplot coordinates {{{' '.join(coordinates['ambiguity_probability'])}}};
    \legend{{Correct deterministic,Wrong deterministic,Honest ambiguity}}
  \end{{axis}}
\end{{tikzpicture}}
"""


def bibliography_tex() -> str:
    return r"""
\begin{thebibliography}{99}
\bibitem{MacKenzieEtAl2002}
MacKenzie, D.I., Nichols, J.D., Lachman, G.B., Droege, S., Royle, J.A., and Langtimm, C.A. (2002).
Estimating site occupancy rates when detection probabilities are less than one.
\emph{Ecology}, 83, 2248--2255.
\url{https://doi.org/10.1890/0012-9658(2002)083[2248:ESORWD]2.0.CO;2}

\bibitem{RoyleLink2006}
Royle, J.A. and Link, W.A. (2006).
Generalized site occupancy models allowing for false positive and false negative errors.
\emph{Ecology}, 87, 835--841.
\url{https://doi.org/10.1890/0012-9658(2006)87[835:GSOMAF]2.0.CO;2}

\bibitem{Manski2003}
Manski, C.F. (2003).
\emph{Partial Identification of Probability Distributions}.
Springer.
\url{https://doi.org/10.1007/b97478}

\bibitem{DormannEtAl2018}
Dormann, C.F. et al. (2018).
Model averaging in ecology: a review of Bayesian, information-theoretic, and tactical approaches for predictive inference.
\emph{Ecological Monographs}, 88, 485--504.
\url{https://doi.org/10.1002/ecm.1309}

\bibitem{Dietze2017}
Dietze, M.C. (2017).
Prediction in ecology: a first-principles framework.
\emph{Ecological Applications}, 27, 2048--2060.
\url{https://doi.org/10.1002/eap.1589}

\bibitem{DietzeEtAl2018}
Dietze, M.C. et al. (2018).
Iterative near-term ecological forecasting: Needs, opportunities, and challenges.
\emph{Proceedings of the National Academy of Sciences USA}, 115, 1424--1432.
\url{https://doi.org/10.1073/pnas.1710231115}

\bibitem{NicholsWilliams2006}
Nichols, J.D. and Williams, B.K. (2006).
Monitoring for conservation.
\emph{Trends in Ecology \& Evolution}, 21, 668--673.
\url{https://doi.org/10.1016/j.tree.2006.08.007}

\bibitem{LindenmayerLikens2009}
Lindenmayer, D.B. and Likens, G.E. (2009).
Adaptive monitoring: a new paradigm for long-term research and monitoring.
\emph{Trends in Ecology \& Evolution}, 24, 482--486.
\url{https://doi.org/10.1016/j.tree.2009.03.005}

\bibitem{Williams2011}
Williams, B.K. (2011).
Adaptive management of natural resources---framework and issues.
\emph{Journal of Environmental Management}, 92, 1346--1353.
\url{https://doi.org/10.1016/j.jenvman.2010.10.041}

\bibitem{ChalonerVerdinelli1995}
Chaloner, K. and Verdinelli, I. (1995).
Bayesian experimental design: A review.
\emph{Statistical Science}, 10, 273--304.
\url{https://doi.org/10.1214/ss/1177009939}

\bibitem{CanessaEtAl2015}
Canessa, S., Guillera-Arroita, G., Lahoz-Monfort, J.J., Southwell, D.M., Armstrong, D.P., Chad\`es, I., Lacy, R.C., and Converse, S.J. (2015).
When do we need more data? A primer on calculating the value of information for applied ecologists.
\emph{Methods in Ecology and Evolution}, 6, 1219--1228.
\url{https://doi.org/10.1111/2041-210X.12423}

\bibitem{GivanDeanGreig2003}
Givan, R., Dean, T., and Greig, M. (2003).
Equivalence notions and model minimization in Markov decision processes.
\emph{Artificial Intelligence}, 147, 163--223.
\url{https://doi.org/10.1016/S0004-3702(02)00376-4}
\end{thebibliography}
"""


def compiled_manuscript_tex(source: str, reviewer_sections: str) -> str:
    package_line = r"\usepackage{amsmath,amssymb,amsthm,booktabs,graphicx,hyperref,listings,xcolor}"
    replacement = package_line + "\n" + r"\usepackage{pgfplots}" + "\n" + r"\pgfplotsset{compat=1.18}"
    if package_line not in source:
        raise RuntimeError("expected manuscript package line was not found")
    source = source.replace(package_line, replacement, 1)
    figure_marker = r"\subsection{Additional dimensions}"
    figures = r"""
\begin{figure}[ht]
\centering
\input{generated/paper_b_experiment_contrast.tex}
\caption{Full-world information gain and prediction-target resolution rank the two follow-up experiments in opposite order.}
\label{fig:experiment-contrast}
\end{figure}

\begin{figure}[ht]
\centering
\input{generated/paper_b_strategy_outcomes.tex}
\caption{Terminal-report probabilities under the validated baseline. Target-safe design resolves the prediction while full-world information gain retains ambiguity after measuring the target-irrelevant attribute.}
\label{fig:strategy-outcomes}
\end{figure}

"""
    if figure_marker not in source:
        raise RuntimeError("benchmark insertion marker was not found")
    source = source.replace(figure_marker, figures + figure_marker, 1)
    discussion_marker = r"\section{Discussion}"
    if discussion_marker not in source:
        raise RuntimeError("discussion insertion marker was not found")
    source = source.replace(discussion_marker, reviewer_sections + "\n" + discussion_marker, 1)
    end_marker = r"\end{document}"
    if end_marker not in source:
        raise RuntimeError("document end marker was not found")
    return source.replace(end_marker, bibliography_tex() + "\n" + end_marker, 1)


def write_outputs() -> dict[str, object]:
    module = runpy.run_path(str(BENCHMARK))
    report = module["run_grid"]()
    if report["schema_version"] != 5:
        raise RuntimeError("figure generator requires benchmark schema version 5")
    runpy.run_path(str(ROBUSTNESS))["run"]()
    bridge_report = runpy.run_path(str(POSTERIOR_BRIDGE))["run"]()
    if bridge_report["schema_version"] != 1:
        raise RuntimeError("posterior bridge schema changed")
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_CONTRAST.write_text(experiment_contrast_tex(report), encoding="utf-8")
    OUT_OUTCOMES.write_text(strategy_outcomes_tex(report), encoding="utf-8")
    source = MANUSCRIPT.read_text(encoding="utf-8")
    reviewer_sections = REVIEWER_SECTIONS.read_text(encoding="utf-8")
    COMPILED_MANUSCRIPT.write_text(
        compiled_manuscript_tex(source, reviewer_sections), encoding="utf-8"
    )
    return report


def main() -> None:
    report = write_outputs()
    print({
        "schema_version": report["schema_version"],
        "outputs": [
            str(OUT_CONTRAST.relative_to(ROOT)),
            str(OUT_OUTCOMES.relative_to(ROOT)),
            str(COMPILED_MANUSCRIPT.relative_to(ROOT)),
        ],
    })


if __name__ == "__main__":
    main()
