"""Generate deterministic Paper B figures and a compiled manuscript source."""
from __future__ import annotations

import runpy
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from ced.detection import OneSidedDetector
from ced.mode_detection import ModeDiverseDetectionPanel
from ced.target_safe_quotient import minimal_target_safe_quotient

BENCHMARK = ROOT / "scripts" / "simulate_paper_b_benchmark.py"
ROBUSTNESS = ROOT / "scripts" / "analyze_paper_b_reviewer_robustness.py"
POSTERIOR_BRIDGE = ROOT / "scripts" / "analyze_paper_b_posterior_bridge.py"
MANUSCRIPT = ROOT / "manuscript" / "paper_b_main.tex"
REVIEWER_SECTIONS = ROOT / "manuscript" / "paper_b_reviewer_sections.tex"
COMPILED_MANUSCRIPT = ROOT / "manuscript" / "paper_b_compiled.tex"
OUT_DIR = ROOT / "manuscript" / "generated"
OUT_CONTRAST = OUT_DIR / "paper_b_experiment_contrast.tex"
OUT_OUTCOMES = OUT_DIR / "paper_b_strategy_outcomes.tex"
OUT_QUOTIENT = OUT_DIR / "paper_b_target_safe_quotient.tex"
OUT_FAILURE = OUT_DIR / "paper_b_failure_architecture.tex"

STRATEGY_LABELS = {
    "state_only": "State-only",
    "full_identification": "Full identification",
    "full_world_eig": "Full-world EIG",
    "target_safe": "Target-safe",
}


def _fmt(value: float) -> str:
    return f"{value:.6f}"


def _baseline_rows(report: dict[str, object]) -> list[dict[str, object]]:
    rows = [
        row for row in report["rows"]
        if row["architecture"] == "independent"
        and row["state_detection_sensitivity"] == 0.95
        and row["response_typing_accuracy"] == 0.99
        and row["common_failure_probability"] == 0.0
    ]
    order = tuple(STRATEGY_LABELS)
    return sorted(rows, key=lambda row: order.index(row["strategy"]))


def experiment_contrast_tex(report: dict[str, object]) -> str:
    contrast = report["benchmark_contrast"]
    gains = contrast["full_world_information_gain_bits"]
    resolutions = contrast["target_resolution_probability"]
    return rf"""% Generated by scripts/render_paper_b_figures.py; do not edit.
\begin{{tikzpicture}}[font=\small]
  \begin{{axis}}[
    ybar, bar width=18pt, width=0.82\linewidth, height=6.2cm,
    ymin=0, ymax=2.15, ylabel={{Information or target resolution}},
    symbolic x coords={{Response experiment,Nuisance experiment}}, xtick=data,
    x tick label style={{align=center}},
    legend style={{at={{(0.5,-0.23)}},anchor=north,legend columns=2}},
    nodes near coords, nodes near coords style={{font=\scriptsize}},
  ]
    \addplot coordinates {{(Response experiment,{_fmt(gains['response'])}) (Nuisance experiment,{_fmt(gains['nuisance'])})}};
    \addplot coordinates {{(Response experiment,{_fmt(resolutions['response'])}) (Nuisance experiment,{_fmt(resolutions['nuisance'])})}};
    \legend{{Full-world information gain (bits),Target-resolution probability}}
  \end{{axis}}
\end{{tikzpicture}}
"""


def strategy_outcomes_tex(report: dict[str, object]) -> str:
    rows = _baseline_rows(report)
    coordinates = {metric: [] for metric in ("correct_probability", "wrong_probability", "ambiguity_probability")}
    for row in rows:
        label = STRATEGY_LABELS[row["strategy"]]
        for metric in coordinates:
            coordinates[metric].append(f"({{{label}}},{_fmt(row[metric])})")
    return rf"""% Generated by scripts/render_paper_b_figures.py; do not edit.
\begin{{tikzpicture}}[font=\small]
  \begin{{axis}}[
    ybar stacked, bar width=22pt, width=0.96\linewidth, height=7cm,
    ymin=0, ymax=1.02, ylabel={{Terminal-report probability}},
    symbolic x coords={{{','.join(STRATEGY_LABELS.values())}}}, xtick=data,
    x tick label style={{rotate=20,anchor=east}},
    legend style={{at={{(0.5,-0.34)}},anchor=north,legend columns=3}},
  ]
    \addplot coordinates {{{' '.join(coordinates['correct_probability'])}}};
    \addplot coordinates {{{' '.join(coordinates['wrong_probability'])}}};
    \addplot coordinates {{{' '.join(coordinates['ambiguity_probability'])}}};
    \legend{{Correct deterministic,Wrong deterministic,Honest ambiguity}}
  \end{{axis}}
\end{{tikzpicture}}
"""


def target_safe_quotient_tex() -> str:
    worlds = ("A0", "A1", "A2", "B0", "B1")
    successors = {
        "A0": "B0",
        "A1": "B0",
        "A2": "B1",
        "B0": "B0",
        "B1": "B1",
    }

    def record(world):
        return world[0]

    def target(world):
        if world == "B0":
            return "recover"
        if world == "B1":
            return "persist"
        return "pending"

    quotient = minimal_target_safe_quotient(
        worlds,
        record,
        target,
        ("treat",),
        lambda world, action: successors[world],
    )
    expected = (("A0", "A1"), ("A2",), ("B0",), ("B1",))
    if quotient.blocks != expected:
        raise RuntimeError("target-safe quotient witness changed")

    return r"""% Generated by scripts/render_paper_b_figures.py; do not edit.
\begin{tikzpicture}[x=1cm,y=1cm,font=\small]
  \node[anchor=east] at (-0.35,2.8) {Current record};
  \node[anchor=east] at (-0.35,1.4) {Target-safe quotient};
  \node[anchor=east] at (-0.35,0.0) {Full latent identity};

  % Fixed latent-world positions.
  \node at (0.35,2.8) {$A_0$}; \node at (1.15,2.8) {$A_1$}; \node at (1.95,2.8) {$A_2$};
  \node at (3.35,2.8) {$B_0$}; \node at (4.15,2.8) {$B_1$};
  \draw[rounded corners] (0.0,2.45) rectangle (2.30,3.15);
  \draw[rounded corners] (3.0,2.45) rectangle (4.50,3.15);

  \node at (0.35,1.4) {$A_0$}; \node at (1.15,1.4) {$A_1$}; \node at (1.95,1.4) {$A_2$};
  \node at (3.35,1.4) {$B_0$}; \node at (4.15,1.4) {$B_1$};
  \draw[rounded corners] (0.0,1.05) rectangle (1.50,1.75);
  \draw[rounded corners] (1.65,1.05) rectangle (2.25,1.75);
  \draw[rounded corners] (3.05,1.05) rectangle (3.65,1.75);
  \draw[rounded corners] (3.85,1.05) rectangle (4.45,1.75);

  \node at (0.35,0.0) {$A_0$}; \node at (1.15,0.0) {$A_1$}; \node at (1.95,0.0) {$A_2$};
  \node at (3.35,0.0) {$B_0$}; \node at (4.15,0.0) {$B_1$};
  \draw[rounded corners] (0.05,-0.35) rectangle (0.65,0.35);
  \draw[rounded corners] (0.85,-0.35) rectangle (1.45,0.35);
  \draw[rounded corners] (1.65,-0.35) rectangle (2.25,0.35);
  \draw[rounded corners] (3.05,-0.35) rectangle (3.65,0.35);
  \draw[rounded corners] (3.85,-0.35) rectangle (4.45,0.35);

  \draw[->] (4.95,2.42) -- node[right,align=left,font=\scriptsize] {refine only when target\\or successor differs} (4.95,1.78);
  \draw[dashed,->] (4.95,1.02) -- node[right,align=left,font=\scriptsize] {extra identity split\\not required for target} (4.95,0.38);
\end{tikzpicture}
"""


def failure_architecture_tex() -> str:
    detector = OneSidedDetector(0.6)
    one_mode = ModeDiverseDetectionPanel(3, 1, 10, 0.8, detector)
    two_modes = ModeDiverseDetectionPanel(3, 2, 5, 0.8, detector)
    if one_mode.total_reads != two_modes.total_reads or one_mode.total_reads != 30:
        raise RuntimeError("equal-effort failure witness changed")

    return rf"""% Generated by scripts/render_paper_b_figures.py; do not edit.
\begin{{tikzpicture}}[font=\small]
  \begin{{axis}}[
    ybar, bar width=24pt, width=0.82\linewidth, height=6.2cm,
    ymin=0, ymax=1.03,
    ylabel={{Certified joint-detection probability}},
    symbolic x coords={{one,two}}, xtick=data,
    xticklabels={{{{1 shared mode\\10 repeats}},{{2 independent modes\\5 repeats}}}},
    x tick label style={{align=center}},
    legend style={{at={{(0.5,-0.25)}},anchor=north,legend columns=2}},
    nodes near coords, nodes near coords style={{font=\scriptsize}},
  ]
    \addplot coordinates {{(one,{_fmt(one_mode.joint_detection_lower_bound)}) (two,{_fmt(two_modes.joint_detection_lower_bound)})}};
    \addplot[only marks,mark=triangle*,mark size=3pt] coordinates {{(one,{_fmt(one_mode.availability_ceiling)}) (two,{_fmt(two_modes.availability_ceiling)})}};
    \legend{{Finite-repeat guarantee,Worst-case guarantee ceiling}}
  \end{{axis}}
  \node[font=\scriptsize,align=center] at (4.2,-1.15) {{3 coordinates; 30 reads in each design; $a\geq0.8$, $p\geq0.6$}};
\end{{tikzpicture}}
"""


def bibliography_tex() -> str:
    return r"""
\begin{thebibliography}{99}
\bibitem{MacKenzieEtAl2002}
MacKenzie, D.I., Nichols, J.D., Lachman, G.B., Droege, S., Royle, J.A., and Langtimm, C.A. (2002).
Estimating site occupancy rates when detection probabilities are less than one.
\emph{Ecology}, 83, 2248--2255.
\url{https://doi.org/10.1890/0012-9658(2002)083[2248:ESORWD]2.0.CO;2}

\bibitem{RoyleLink2006}
Royle, J.A. and Link, W.A. (2006).
Generalized site occupancy models allowing for false positive and false negative errors.
\emph{Ecology}, 87, 835--841.
\url{https://doi.org/10.1890/0012-9658(2006)87[835:GSOMAF]2.0.CO;2}

\bibitem{Manski2003}
Manski, C.F. (2003).
\emph{Partial Identification of Probability Distributions}.
Springer.
\url{https://doi.org/10.1007/b97478}

\bibitem{DormannEtAl2018}
Dormann, C.F. et al. (2018).
Model averaging in ecology: a review of Bayesian, information-theoretic, and tactical approaches for predictive inference.
\emph{Ecological Monographs}, 88, 485--504.
\url{https://doi.org/10.1002/ecm.1309}

\bibitem{Dietze2017}
Dietze, M.C. (2017).
Prediction in ecology: a first-principles framework.
\emph{Ecological Applications}, 27, 2048--2060.
\url{https://doi.org/10.1002/eap.1589}

\bibitem{DietzeEtAl2018}
Dietze, M.C. et al. (2018).
Iterative near-term ecological forecasting: Needs, opportunities, and challenges.
\emph{Proceedings of the National Academy of Sciences USA}, 115, 1424--1432.
\url{https://doi.org/10.1073/pnas.1710231115}

\bibitem{NicholsWilliams2006}
Nichols, J.D. and Williams, B.K. (2006).
Monitoring for conservation.
\emph{Trends in Ecology \& Evolution}, 21, 668--673.
\url{https://doi.org/10.1016/j.tree.2006.08.007}

\bibitem{LindenmayerLikens2009}
Lindenmayer, D.B. and Likens, G.E. (2009).
Adaptive monitoring: a new paradigm for long-term research and monitoring.
\emph{Trends in Ecology \& Evolution}, 24, 482--486.
\url{https://doi.org/10.1016/j.tree.2009.03.005}

\bibitem{Williams2011}
Williams, B.K. (2011).
Adaptive management of natural resources---framework and issues.
\emph{Journal of Environmental Management}, 92, 1346--1353.
\url{https://doi.org/10.1016/j.jenvman.2010.10.041}

\bibitem{ChalonerVerdinelli1995}
Chaloner, K. and Verdinelli, I. (1995).
Bayesian experimental design: A review.
\emph{Statistical Science}, 10, 273--304.
\url{https://doi.org/10.1214/ss/1177009939}

\bibitem{CanessaEtAl2015}
Canessa, S., Guillera-Arroita, G., Lahoz-Monfort, J.J., Southwell, D.M., Armstrong, D.P., Chad\`es, I., Lacy, R.C., and Converse, S.J. (2015).
When do we need more data? A primer on calculating the value of information for applied ecologists.
\emph{Methods in Ecology and Evolution}, 6, 1219--1228.
\url{https://doi.org/10.1111/2041-210X.12423}

\bibitem{GivanDeanGreig2003}
Givan, R., Dean, T., and Greig, M. (2003).
Equivalence notions and model minimization in Markov decision processes.
\emph{Artificial Intelligence}, 147, 163--223.
\url{https://doi.org/10.1016/S0004-3702(02)00376-4}
\end{thebibliography}
"""


def compiled_manuscript_tex(source: str, reviewer_sections: str) -> str:
    package_line = r"\usepackage{amsmath,amssymb,amsthm,booktabs,graphicx,hyperref,listings,xcolor}"
    replacement = package_line + "\n" + r"\usepackage{pgfplots}" + "\n" + r"\pgfplotsset{compat=1.18}"
    if package_line not in source:
        raise RuntimeError("expected manuscript package line was not found")
    source = source.replace(package_line, replacement, 1)

    result3_marker = r"\subsection{Result 3: failure architecture determines trustworthy refinement}"
    quotient_figure = r"""
\begin{figure}[ht]
\centering
\input{generated/paper_b_target_safe_quotient.tex}
\caption{Three levels of latent-state resolution for a five-world witness. The current record cannot separate the $A$ worlds or the $B$ worlds. Target-safe refinement splits only the classes needed to preserve the declared target under treatment; full latent identity additionally separates $A_0$ from $A_1$ although that distinction changes neither target nor declared successor.}
\label{fig:target-safe-quotient}
\end{figure}

"""
    if result3_marker not in source:
        raise RuntimeError("Result 3 insertion marker was not found")
    source = source.replace(result3_marker, quotient_figure + result3_marker, 1)

    result4_marker = r"\subsection{Result 4: adaptive risk-limited target resolution}"
    failure_figure = r"""
\begin{figure}[ht]
\centering
\input{generated/paper_b_failure_architecture.tex}
\caption{Equal nominal effort can provide different certified evidence under different failure architectures. Both designs use 30 reads across three coordinates with sensitivity lower bound 0.6 and mode-availability lower bound 0.8. The plotted triangles are worst-case guarantee ceilings implied by the lower-bound contract, not universal upper bounds on realized detection when actual availability is higher.}
\label{fig:failure-architecture}
\end{figure}

"""
    if result4_marker not in source:
        raise RuntimeError("Result 4 insertion marker was not found")
    source = source.replace(result4_marker, failure_figure + result4_marker, 1)

    figure_marker = r"\subsection{Additional dimensions}"
    figures = r"""
\begin{figure}[ht]
\centering
\input{generated/paper_b_experiment_contrast.tex}
\caption{Full-world information gain and prediction-target resolution rank the two follow-up experiments in opposite order.}
\label{fig:experiment-contrast}
\end{figure}

\begin{figure}[ht]
\centering
\input{generated/paper_b_strategy_outcomes.tex}
\caption{Terminal-report probabilities under the validated baseline. Target-safe design resolves the prediction while full-world information gain retains ambiguity after measuring the target-irrelevant attribute.}
\label{fig:strategy-outcomes}
\end{figure}

"""
    if figure_marker not in source:
        raise RuntimeError("benchmark insertion marker was not found")
    source = source.replace(figure_marker, figures + figure_marker, 1)
    discussion_marker = r"\section{Discussion}"
    if discussion_marker not in source:
        raise RuntimeError("discussion insertion marker was not found")
    source = source.replace(discussion_marker, reviewer_sections + "\n" + discussion_marker, 1)
    end_marker = r"\end{document}"
    if end_marker not in source:
        raise RuntimeError("document end marker was not found")
    return source.replace(end_marker, bibliography_tex() + "\n" + end_marker, 1)


def write_outputs() -> dict[str, object]:
    module = runpy.run_path(str(BENCHMARK))
    report = module["run_grid"]()
    if report["schema_version"] != 5:
        raise RuntimeError("figure generator requires benchmark schema version 5")
    runpy.run_path(str(ROBUSTNESS))["run"]()
    bridge_report = runpy.run_path(str(POSTERIOR_BRIDGE))["run"]()
    if bridge_report["schema_version"] != 1:
        raise RuntimeError("posterior bridge schema changed")
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_CONTRAST.write_text(experiment_contrast_tex(report), encoding="utf-8")
    OUT_OUTCOMES.write_text(strategy_outcomes_tex(report), encoding="utf-8")
    OUT_QUOTIENT.write_text(target_safe_quotient_tex(), encoding="utf-8")
    OUT_FAILURE.write_text(failure_architecture_tex(), encoding="utf-8")
    source = MANUSCRIPT.read_text(encoding="utf-8")
    reviewer_sections = REVIEWER_SECTIONS.read_text(encoding="utf-8")
    COMPILED_MANUSCRIPT.write_text(
        compiled_manuscript_tex(source, reviewer_sections), encoding="utf-8"
    )
    return report


def main() -> None:
    report = write_outputs()
    print({
        "schema_version": report["schema_version"],
        "outputs": [
            str(OUT_CONTRAST.relative_to(ROOT)),
            str(OUT_OUTCOMES.relative_to(ROOT)),
            str(OUT_QUOTIENT.relative_to(ROOT)),
            str(OUT_FAILURE.relative_to(ROOT)),
            str(COMPILED_MANUSCRIPT.relative_to(ROOT)),
        ],
    })


if __name__ == "__main__":
    main()
